package com.witontek.ehospital;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-18T09:39:06.248+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://www.witontek.com/ehospital/", name = "IWindowPayWebServiceV2")
@XmlSeeAlso({ObjectFactory.class})
public interface IWindowPayWebServiceV2 {

    @WebMethod(action = "http://www.witontek.com/ehospital/qryPayStatus")
    @RequestWrapper(localName = "qryPayStatus", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.QryPayStatus")
    @ResponseWrapper(localName = "qryPayStatusResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.QryPayStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String qryPayStatus(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/scanRefund")
    @RequestWrapper(localName = "scanRefund", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.ScanRefund")
    @ResponseWrapper(localName = "scanRefundResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.ScanRefundResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String scanRefund(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/microPay")
    @RequestWrapper(localName = "microPay", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.MicroPay")
    @ResponseWrapper(localName = "microPayResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.MicroPayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String microPay(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/refund")
    @RequestWrapper(localName = "refund", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.Refund")
    @ResponseWrapper(localName = "refundResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.RefundResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String refund(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/qryOrderStatus")
    @RequestWrapper(localName = "qryOrderStatus", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.QryOrderStatus")
    @ResponseWrapper(localName = "qryOrderStatusResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.QryOrderStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String qryOrderStatus(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/createOrder")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.CreateOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String createOrder(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/queryRefundStatus")
    @RequestWrapper(localName = "queryRefundStatus", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.QueryRefundStatus")
    @ResponseWrapper(localName = "queryRefundStatusResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.QueryRefundStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String queryRefundStatus(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/reverseOrder")
    @RequestWrapper(localName = "reverseOrder", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.ReverseOrder")
    @ResponseWrapper(localName = "reverseOrderResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.ReverseOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String reverseOrder(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/qrCodeReverse")
    @RequestWrapper(localName = "qrCodeReverse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.QrCodeReverse")
    @ResponseWrapper(localName = "qrCodeReverseResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.QrCodeReverseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String qrCodeReverse(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/refundReverse")
    @RequestWrapper(localName = "refundReverse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.RefundReverse")
    @ResponseWrapper(localName = "refundReverseResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.RefundReverseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String refundReverse(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/qryRefund")
    @RequestWrapper(localName = "qryRefund", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.QryRefund")
    @ResponseWrapper(localName = "qryRefundResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.QryRefundResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String qryRefund(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebMethod(action = "http://www.witontek.com/ehospital/closeOrder")
    @RequestWrapper(localName = "closeOrder", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.CloseOrder")
    @ResponseWrapper(localName = "closeOrderResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "com.witontek.ehospital.CloseOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String closeOrder(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );
}
